artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/muhammadmaazsayyed/chicken-disease-dataset/download?datasetVersionNumber=1
  unzip_dir: artifacts/data_ingestion
  kaggle_api_key: .kaggle/kaggle.json



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 ## Top Flatten layers added
  


